#
# ==== General info ====
#
# * After editing of this file you need to check server logs to be
# sure that no errors was appeared.
#

#
# Show debug info. Possible values: true | false (default = false)
#
# This option can affect the performance.
#
debug: false

# WARNING: Don't change the name, don't include it into 'explosion-boosters'
EGG-SYSTEM:
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/FireworkEffect.Type.html
  effect: STAR
  # <integer:1..31>
  duration-per-item: 5
  # <integer:1..2047>
  power-per-item: 1

explosion-boosters:
  - TNT
  - END_CRYSTAL
  - NETHER_STAR
  - HEAVY_CORE
  # To add your own explosion boosters, refer to other entity types:
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html

TNT:
  effect: BURST
  duration-per-item: 1
  power-per-item: 1

END_CRYSTAL:
  effect: BALL
  duration-per-item: 2
  power-per-item: 2

NETHER_STAR:
  effect: BALL_LARGE
  duration-per-item: 5
  power-per-item: 20

HEAVY_CORE:
  effect: CREEPER
  duration-per-item: 10
  power-per-item: 50

#
# Broadcast 'Nuclear launch detected'
# when an explosion power is bigger
# than this threshold.
#
# <integer:17..16384>
#
# 17 is the minimum explosion power when "nuclear" mechanic is used.
#
nuke-broadcast-threshold: 17